restylers:
  - isort:
      enabled: false
  - reorder-python-imports:
      enabled: false
  - autopep8:
      enabled: false
  - yapf:
      enabled: false
  - prettier-markdown:
      arguments: ["--prose-wrap", "preserve"]
  - "*"
